project:
  type: website
  output-dir: docs

website: 
  page-navigation: true
  title: "CV & Projets" 
  site-url: "https://noalrx.github.io/portfolio/" 
  repo-url: "https://github.com/NoaLRX/portfolio"
  repo-actions: [edit, issue]
  
  page-footer:
    right: "Cette page a été faite avec ❤️ et [Quarto](https://quarto.org/)."
    
  sidebar:
    round-logo: true
    logo: "meduse.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/NoaLRX
        text: "GitHub"
      - icon: linkedin
        href : https://www.linkedin.com/in/noa-le-roux/
        text: "Linkedin"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Mes projets
      - href: about.qmd
        text: Qui suis-je ?

format:
  html:
    theme:
      light: [simplex, theme.scss]
      dark: [simplex, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-location: right

toc: true
toc-location: right

editor: visual
